### ISSUE TITLE
Create groups a user can join

### ISSUE THREAD

**Issue by MJZwart** [MJZwart/motivation-app#189]
- [x] #190
- [x] #191
- [x] #192

For now the functionality is basic, just join a group, make one or leave. More functionality will follow. A user will be able to have and join multiple groups, not sure if I'll make a max yet. Probably.

**Comment by LaEve** [comment]
currently everything is finished according to specifications.
problems:
1. can't join a private group
2. can join any group if you guess the group id
3. when searching through all groups it also shows groups you already are a member of

suggestions:
1. add an invite system
    - "invite friend" button on group panel, brings up a list of friends not in group with invite button next to each friend (or cancel invite if already invited)
    - "invite" button on profile of other users, brings up list of groups you are in to invite that user to the group(s) (or cancel invite if already invited)
    - add "invited" list to see all groups you are invited to (with buttons to accept or decline)
    - on public group list, add "invited" notification to the groups you are invited to with button to accept or decline
    - would remove problem 1. and 2.
2. on own group view, add button with modal to edit group (if you admin)
