### ISSUE TITLE
Allow for the admin to interact with the bug report.

### ISSUE THREAD

**Issue by MJZwart** [MJZwart/motivation-app#220]
- [x] Add a form to edit the bug report (changing status, adding comment, changing severity, changing type) Possibly a modal

Can only be done after messaging system is implemented: (#195)
- [x] Add an optional form with textarea to send a message to the user who reported the bug

- [x] Upon setting a bug report on resolved, automatically send a notification to the user who reported it to say that the bug has been resolved

**Comment by LaEve** [comment]
BugReportController@update responds with all bug reports, which then get loaded into the store
possibly change to:
-  call fetchBugReports inside updateBugReport the store, and have BugReportController@update only respond with text msg
- load the bug reports new after closing the editing modal (after actually editing, not after canceling out of the modal)
- BugReportController@update only responds with text msg and the one updated bug report which then gets updated on the page (no idea how)
